[package]
name = "solana-bpf-loader-program"
version = "1.3.10"
description = "Solana BPF loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.3.1"
byteorder = "1.3.4"
<<<<<<< HEAD
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
solana-runtime = { path = "../../runtime", version = "1.3.10" }
solana-sdk = { path = "../../sdk", version = "1.3.10" }
solana_rbpf = "=0.1.30"
=======
num-derive = "0.3"
num-traits = "0.2"
solana-runtime = { path = "../../runtime", version = "1.4.0" }
solana-sdk = { path = "../../sdk", version = "1.4.0" }
solana_rbpf = "=0.1.31"
>>>>>>> 3278d78f0... Cache re-usable work performed by the loader (#12135)
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
rustversion = "1.0.3"

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
